- hosts: backup
  tasks:
    - name: install rsync
      script: ./backup.sh
    - name: backup_server
      cron: name=backup_server minute=00 hour=01 job='/bin/sh /server/scripts/backup_server.sh &>/dev/null'
- hosts: nfs
  tasks:
    - name: install nfs rpc
      script: ./nfs.sh
    - name: backup_nfs
      cron: name=backup_nfs minute=00 hour=00 job='/bin/sh /server/scripts/backup_nfs.sh &>/dev/null'
- hosts: db
  tasks:
    - name: creat /server/tools
      file: path=/server/tools state=directory
    - name: copy mysql
      copy: src=mysql-5.6.34-linux-glibc2.5-x86_64.tar.gz dest=/server/tools/
    - name: install mysql
      script: ./db01.sh
- hosts: 10.0.0.8
  tasks:
    - name: creat /server/tools
      file: path=/server/tools state=directory
    - name: copy dedecms discuz wordpress php
      copy: src={{ item }} dest=/server/tools/
      with_item:
        - DedeCMS-V5.7-UTF8-SP2.tar.gz
        - Discuz_X3.2_SC_UTF8.zip
        - wordpress-4.7.3-zh_CN.tar.gz
        - php-5.5.32.tar.gz
      - name: install nginx php nfs rpc
      script: ./web01.sh
    - name: backup_web
      cron: name=backup_nfs minute=00 hour=00 job='/bin/sh /server/scripts/backup_web.sh &>/dev/null'
- hosts: lb01
  tasks:
    - name: creat /server/tools
      file: path=/server/tools state=directory
    - name: install nginx
      script: /root/LNMP/lb01.sh
- hosts: lb02
  tasks:
    - name: creat /server/tools
      file: path=/server/tools state=directory
    - name: install nginx
      script: ./lb02.sh