- hosts: backup
  tasks:
    - name: install rsync
      script: /root/LNMP/backup.sh
- hosts: nfs
  tasks:
    - name: install nfs rpc
      script: /root/LNMP/nfs.sh
- hosts: db
  tasks:
    - name: install mysql
      script: /root/LNMP/db01.sh
- hosts: web
  tasks:
    - name: install nginx php wordpress nfs rpc
      script: /root/LNMP/web01.sh
- hosts: lb
  tasks:
    - name: install nginx
      script: /root/LNMP/lb01.sh